# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('nationality_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10, verbose_name='Login')),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=8)),
                ('cellphone', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=9)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivileges',
            fields=[
                ('user_privileges_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('identification_number', models.CharField(max_length=10)),
                ('resident', models.BooleanField()),
                ('last_address', models.CharField(max_length=30)),
                ('fk_nationality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nationality')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fk_user_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserType'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='fk_user_privileges_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserPrivileges'),
        ),
    ]
