# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fk_user_privileges_id',
            new_name='fk_user_privileges',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='fk_user_type_id',
            new_name='fk_user_type',
        ),
        migrations.RenameField(
            model_name='usertype',
            old_name='fk_nationality_id',
            new_name='fk_nationality',
        ),
    ]
