# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_info_id',
            new_name='user_info',
        ),
    ]
