# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='first_name',
        ),
    ]
