# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_info',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
