# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10)),
                ('kitchen', models.BooleanField()),
                ('study_room', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('door_number', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('share', models.BooleanField()),
                ('fk_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Place')),
            ],
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('room_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('bathroom_inside', models.BooleanField()),
                ('bath', models.BooleanField()),
                ('double_bed', models.BooleanField()),
                ('study_table', models.BooleanField()),
                ('closet', models.BooleanField()),
                ('tv', models.BooleanField()),
                ('mirror', models.BooleanField()),
                ('nightstand', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomSize',
            fields=[
                ('room_size_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='roominfo',
            name='fk_room_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RoomSize'),
        ),
        migrations.AddField(
            model_name='room',
            name='fk_room_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RoomInfo'),
        ),
    ]
