--------- FK ---------

ALTER TABLE app_userinfo
ADD FOREIGN KEY(user_info_id)
REFERENCES app_user (user_id)
ON DELETE CASCADE;


--------- Insert app_user_privileges ---------

insert into app_userprivileges (description) values ('administrador');
insert into app_userprivileges (description) values ('cliente');

--------- Insert app_nationality ---------

insert into app_nationality (country) values ('Afeganistão');
insert into app_nationality (country) values ('África do Sul');
insert into app_nationality (country) values ('Akrotiri');
insert into app_nationality (country) values ('Albânia');
insert into app_nationality (country) values ('Alemanha');
insert into app_nationality (country) values ('Andorra');
insert into app_nationality (country) values ('Angola');
insert into app_nationality (country) values ('Anguila');
insert into app_nationality (country) values ('Antárctida');
insert into app_nationality (country) values ('Antígua e Barbuda');
insert into app_nationality (country) values ('Antilhas Neerlandesas');
insert into app_nationality (country) values ('Arábia Saudita');
insert into app_nationality (country) values ('Arctic Ocean');
insert into app_nationality (country) values ('Argélia');
insert into app_nationality (country) values ('Argentina');
insert into app_nationality (country) values ('Arménia');
insert into app_nationality (country) values ('Aruba');
insert into app_nationality (country) values ('Ashmore and Cartier Islands');
insert into app_nationality (country) values ('Atlantic Ocean');
insert into app_nationality (country) values ('Austrália');
insert into app_nationality (country) values ('Áustria');
insert into app_nationality (country) values ('Azerbaijão');
insert into app_nationality (country) values ('Baamas');
insert into app_nationality (country) values ('Bangladeche');
insert into app_nationality (country) values ('Barbados');
insert into app_nationality (country) values ('Barém');
insert into app_nationality (country) values ('Bélgica');
insert into app_nationality (country) values ('Belize');
insert into app_nationality (country) values ('Benim');
insert into app_nationality (country) values ('Bermudas');
insert into app_nationality (country) values ('Bielorrússia');
insert into app_nationality (country) values ('Birmânia');
insert into app_nationality (country) values ('Bolívia');
insert into app_nationality (country) values ('Bósnia e Herzegovina');
insert into app_nationality (country) values ('Botsuana');
insert into app_nationality (country) values ('Brasil');
insert into app_nationality (country) values ('Brunei');
insert into app_nationality (country) values ('Bulgária');
insert into app_nationality (country) values ('Burquina Faso');
insert into app_nationality (country) values ('Burúndi');
insert into app_nationality (country) values ('Butão');
insert into app_nationality (country) values ('Cabo Verde');
insert into app_nationality (country) values ('Camarões');
insert into app_nationality (country) values ('Camboja');
insert into app_nationality (country) values ('Canadá');
insert into app_nationality (country) values ('Catar');
insert into app_nationality (country) values ('Cazaquistão');
insert into app_nationality (country) values ('Chade');
insert into app_nationality (country) values ('Chile');
insert into app_nationality (country) values ('China');
insert into app_nationality (country) values ('Chipre');
insert into app_nationality (country) values ('Clipperton Island');
insert into app_nationality (country) values ('Colômbia');
insert into app_nationality (country) values ('Comores');
insert into app_nationality (country) values ('Congo-Brazzaville');
insert into app_nationality (country) values ('Congo-Kinshasa');
insert into app_nationality (country) values ('Coral Sea Islands');
insert into app_nationality (country) values ('Coreia do Norte');
insert into app_nationality (country) values ('Coreia do Sul');
insert into app_nationality (country) values ('Costa do Marfim');
insert into app_nationality (country) values ('Costa Rica');
insert into app_nationality (country) values ('Croácia');
insert into app_nationality (country) values ('Cuba');
insert into app_nationality (country) values ('Dhekelia');
insert into app_nationality (country) values ('Dinamarca');
insert into app_nationality (country) values ('Domínica');
insert into app_nationality (country) values ('Egipto');
insert into app_nationality (country) values ('El Salvador');
insert into app_nationality (country) values ('Emiratos Árabes Unidos');
insert into app_nationality (country) values ('Equador');
insert into app_nationality (country) values ('Eritreia');
insert into app_nationality (country) values ('Eslováquia');
insert into app_nationality (country) values ('Eslovénia');
insert into app_nationality (country) values ('Espanha');
insert into app_nationality (country) values ('Estados Unidos');
insert into app_nationality (country) values ('Estónia');
insert into app_nationality (country) values ('Etiópia');
insert into app_nationality (country) values ('Faroé');
insert into app_nationality (country) values ('Fiji');
insert into app_nationality (country) values ('Filipinas');
insert into app_nationality (country) values ('Finlândia');
insert into app_nationality (country) values ('França');
insert into app_nationality (country) values ('Gabão');
insert into app_nationality (country) values ('Gâmbia');
insert into app_nationality (country) values ('Gana');
insert into app_nationality (country) values ('Gaza Strip');
insert into app_nationality (country) values ('Geórgia');
insert into app_nationality (country) values ('Geórgia do Sul e Sandwich do Sul');
insert into app_nationality (country) values ('Gibraltar');
insert into app_nationality (country) values ('Granada');
insert into app_nationality (country) values ('Grécia');
insert into app_nationality (country) values ('Gronelândia');
insert into app_nationality (country) values ('Guame');
insert into app_nationality (country) values ('Guatemala');
insert into app_nationality (country) values ('Guernsey');
insert into app_nationality (country) values ('Guiana');
insert into app_nationality (country) values ('Guiné');
insert into app_nationality (country) values ('Guiné Equatorial');
insert into app_nationality (country) values ('Guiné-Bissau');
insert into app_nationality (country) values ('Haiti');
insert into app_nationality (country) values ('Honduras');
insert into app_nationality (country) values ('Hong Kong');
insert into app_nationality (country) values ('Hungria');
insert into app_nationality (country) values ('Iémen');
insert into app_nationality (country) values ('Ilha Bouvet');
insert into app_nationality (country) values ('Ilha do Natal');
insert into app_nationality (country) values ('Ilha Norfolk');
insert into app_nationality (country) values ('Ilhas Caimão');
insert into app_nationality (country) values ('Ilhas Cook');
insert into app_nationality (country) values ('Ilhas dos Cocos');
insert into app_nationality (country) values ('Ilhas Falkland');
insert into app_nationality (country) values ('Ilhas Heard e McDonald');
insert into app_nationality (country) values ('Ilhas Marshall');
insert into app_nationality (country) values ('Ilhas Salomão');
insert into app_nationality (country) values ('Ilhas Turcas e Caicos');
insert into app_nationality (country) values ('Ilhas Virgens Americanas');
insert into app_nationality (country) values ('Ilhas Virgens Britânicas');
insert into app_nationality (country) values ('Índia');
insert into app_nationality (country) values ('Indian Ocean');
insert into app_nationality (country) values ('Indonésia');
insert into app_nationality (country) values ('Irão');
insert into app_nationality (country) values ('Iraque');
insert into app_nationality (country) values ('Irlanda');
insert into app_nationality (country) values ('Islândia');
insert into app_nationality (country) values ('Israel');
insert into app_nationality (country) values ('Itália');
insert into app_nationality (country) values ('Jamaica');
insert into app_nationality (country) values ('Jan Mayen');
insert into app_nationality (country) values ('Japão');
insert into app_nationality (country) values ('Jersey');
insert into app_nationality (country) values ('Jibuti');
insert into app_nationality (country) values ('Jordânia');
insert into app_nationality (country) values ('Kuwait');
insert into app_nationality (country) values ('Laos');
insert into app_nationality (country) values ('Lesoto');
insert into app_nationality (country) values ('Letónia');
insert into app_nationality (country) values ('Líbano');
insert into app_nationality (country) values ('Libéria');
insert into app_nationality (country) values ('Líbia');
insert into app_nationality (country) values ('Listenstaine');
insert into app_nationality (country) values ('Lituânia');
insert into app_nationality (country) values ('Luxemburgo');
insert into app_nationality (country) values ('Macau');
insert into app_nationality (country) values ('Macedónia');
insert into app_nationality (country) values ('Madagáscar');
insert into app_nationality (country) values ('Malásia');
insert into app_nationality (country) values ('Malávi');
insert into app_nationality (country) values ('Maldivas');
insert into app_nationality (country) values ('Mali');
insert into app_nationality (country) values ('Malta');
insert into app_nationality (country) values ('Man, Isle of');
insert into app_nationality (country) values ('Marianas do Norte');
insert into app_nationality (country) values ('Marrocos');
insert into app_nationality (country) values ('Maurícia');
insert into app_nationality (country) values ('Mauritânia');
insert into app_nationality (country) values ('Mayotte');
insert into app_nationality (country) values ('México');
insert into app_nationality (country) values ('Micronésia');
insert into app_nationality (country) values ('Moçambique');
insert into app_nationality (country) values ('Moldávia');
insert into app_nationality (country) values ('Mónaco');
insert into app_nationality (country) values ('Mongólia');
insert into app_nationality (country) values ('Monserrate');
insert into app_nationality (country) values ('Montenegro');
insert into app_nationality (country) values ('Mundo');
insert into app_nationality (country) values ('Namíbia');
insert into app_nationality (country) values ('Nauru');
insert into app_nationality (country) values ('Navassa Island');
insert into app_nationality (country) values ('Nepal');
insert into app_nationality (country) values ('Nicarágua');
insert into app_nationality (country) values ('Níger');
insert into app_nationality (country) values ('Nigéria');
insert into app_nationality (country) values ('Niue');
insert into app_nationality (country) values ('Noruega');
insert into app_nationality (country) values ('Nova Caledónia');
insert into app_nationality (country) values ('Nova Zelândia');
insert into app_nationality (country) values ('Omã');
insert into app_nationality (country) values ('Pacific Ocean');
insert into app_nationality (country) values ('Países Baixos');
insert into app_nationality (country) values ('Palau');
insert into app_nationality (country) values ('Panamá');
insert into app_nationality (country) values ('Papua-Nova Guiné');
insert into app_nationality (country) values ('Paquistão');
insert into app_nationality (country) values ('Paracel Islands');
insert into app_nationality (country) values ('Paraguai');
insert into app_nationality (country) values ('Peru');
insert into app_nationality (country) values ('Pitcairn');
insert into app_nationality (country) values ('Polinésia Francesa');
insert into app_nationality (country) values ('Polónia');
insert into app_nationality (country) values ('Porto Rico');
insert into app_nationality (country) values ('Portugal');
insert into app_nationality (country) values ('Quénia');
insert into app_nationality (country) values ('Quirguizistão');
insert into app_nationality (country) values ('Quiribáti');
insert into app_nationality (country) values ('Reino Unido');
insert into app_nationality (country) values ('República Centro-Africana');
insert into app_nationality (country) values ('República Checa');
insert into app_nationality (country) values ('República Dominicana');
insert into app_nationality (country) values ('Roménia');
insert into app_nationality (country) values ('Ruanda');
insert into app_nationality (country) values ('Rússia');
insert into app_nationality (country) values ('Samoa');
insert into app_nationality (country) values ('Samoa Americana');
insert into app_nationality (country) values ('Santa Helena');
insert into app_nationality (country) values ('Santa Lúcia');
insert into app_nationality (country) values ('São Cristóvão e Neves');
insert into app_nationality (country) values ('São Marinho');
insert into app_nationality (country) values ('São Pedro e Miquelon');
insert into app_nationality (country) values ('São Tomé e Príncipe');
insert into app_nationality (country) values ('São Vicente e Granadinas');
insert into app_nationality (country) values ('Sara Ocidental');
insert into app_nationality (country) values ('Seicheles');
insert into app_nationality (country) values ('Senegal');
insert into app_nationality (country) values ('Serra Leoa');
insert into app_nationality (country) values ('Sérvia');
insert into app_nationality (country) values ('Singapura');
insert into app_nationality (country) values ('Síria');
insert into app_nationality (country) values ('Somália');
insert into app_nationality (country) values ('Southern Ocean');
insert into app_nationality (country) values ('Spratly Islands');
insert into app_nationality (country) values ('Sri Lanca');
insert into app_nationality (country) values ('Suazilândia');
insert into app_nationality (country) values ('Sudão');
insert into app_nationality (country) values ('Suécia');
insert into app_nationality (country) values ('Suíça');
insert into app_nationality (country) values ('Suriname');
insert into app_nationality (country) values ('Svalbard e Jan Mayen');
insert into app_nationality (country) values ('Tailândia');
insert into app_nationality (country) values ('Taiwan');
insert into app_nationality (country) values ('Tajiquistão');
insert into app_nationality (country) values ('Tanzânia');
insert into app_nationality (country) values ('Território Britânico do Oceano Índico');
insert into app_nationality (country) values ('Territórios Austrais Franceses');
insert into app_nationality (country) values ('Timor Leste');
insert into app_nationality (country) values ('Togo');
insert into app_nationality (country) values ('Tokelau');
insert into app_nationality (country) values ('Tonga');
insert into app_nationality (country) values ('Trindade e Tobago');
insert into app_nationality (country) values ('Tunísia');
insert into app_nationality (country) values ('Turquemenistão');
insert into app_nationality (country) values ('Turquia');
insert into app_nationality (country) values ('Tuvalu');
insert into app_nationality (country) values ('Ucrânia');
insert into app_nationality (country) values ('Uganda');
insert into app_nationality (country) values ('União Europeia');
insert into app_nationality (country) values ('Uruguai');
insert into app_nationality (country) values ('Usbequistão');
insert into app_nationality (country) values ('Vanuatu');
insert into app_nationality (country) values ('Vaticano');
insert into app_nationality (country) values ('Venezuela');
insert into app_nationality (country) values ('Vietname');
insert into app_nationality (country) values ('Wake Island');
insert into app_nationality (country) values ('Wallis e Futuna');
insert into app_nationality (country) values ('West Bank');
insert into app_nationality (country) values ('Zâmbia');
insert into app_nationality (country) values ('Zimbabué');

--------- Selects ---------

select * from app_nationality;
select * from app_userprivileges;

select * from app_user;
select * from app_usertype;
select * from app_userinfo;
